/* Generated by re2c 3.0 on Sun Mar 27 12:51:23 2022 */
#line 1 "./tokenizer.re2c"
/*
    Usage: re2c --tags ./tokenizer.re2c -o Tokenizer.cpp
*/

#include "Tokenizer.h"
#include <cstdio>
#include <string>
#include <vector>
#include <stack>
#include "Token.h"
#include <iostream>

using namespace std;

int whiteCount(char* line, char* end) {
  int count = 0;
  while (line != end) {
      if (*line == ' ') {
          count++;
      } else if (*line == '\t') {
          count += 4;
      }
      line++;
  }
  return count;
}

void processIndent(vector<Token>& toks, stack<int>& ind, int& nesting, char* line, char* end) {
  if (nesting)
    return;

  int indent = whiteCount(line, end);

  if (indent == ind.top()) {
      return;
  }

  if (indent > ind.top()) {
    toks.push_back(Token(TokenType::NEWLINE));
    toks.push_back(Token(TokenType::INDENT, string(indent, ' ')));
    ind.push(indent);
    return;
  }

  while (indent < ind.top()) {
    ind.pop();
    toks.push_back(Token(TokenType::NEWLINE));
    toks.push_back(Token(TokenType::DEDENT));
  }
}

vector<Token> Tokenizer::tokenize(const string& input) {
    const char* str = input.c_str();
    vector<Token> tokens;
    int nesting = 0;
    stack<int> ind;
    ind.push(0);
    const char *YYCURSOR = str;
    const char* YYMARKER;
    const char *t1, *t2, *t3;
again:
    
#line 66 "Tokenizer.cpp"
const char *yyt1;
const char *yyt2;
#line 62 "./tokenizer.re2c"

    
#line 72 "Tokenizer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t': goto yy4;
		case '\n': goto yy5;
		case ' ': goto yy7;
		case '!': goto yy8;
		case '"':
			yyt1 = YYCURSOR;
			goto yy9;
		case '#': goto yy11;
		case '%': goto yy13;
		case '&': goto yy15;
		case '\'':
			yyt1 = YYCURSOR;
			goto yy17;
		case '(': goto yy19;
		case ')': goto yy20;
		case '*': goto yy21;
		case '+': goto yy23;
		case ',': goto yy25;
		case '-': goto yy26;
		case '.': goto yy28;
		case '/': goto yy30;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
			yyt1 = YYCURSOR;
			goto yy32;
		case ':': goto yy34;
		case ';': goto yy36;
		case '<': goto yy37;
		case '=': goto yy39;
		case '>': goto yy41;
		case '@': goto yy43;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
			yyt1 = YYCURSOR;
			goto yy45;
		case '[': goto yy47;
		case ']': goto yy48;
		case '^': goto yy49;
		case '{': goto yy51;
		case '|': goto yy52;
		case '}': goto yy54;
		case '~': goto yy55;
		default: goto yy2;
	}
yy1:
	++YYCURSOR;
#line 170 "./tokenizer.re2c"
	{
            processIndent(tokens, ind, nesting, (char*)YYCURSOR, (char*)YYCURSOR);
            tokens.push_back(Token(TokenType::ENDMARKER));
        }
#line 189 "Tokenizer.cpp"
yy2:
	++YYCURSOR;
yy3:
#line 175 "./tokenizer.re2c"
	{ goto done; }
#line 195 "Tokenizer.cpp"
yy4:
	++YYCURSOR;
#line 166 "./tokenizer.re2c"
	{ goto again; }
#line 200 "Tokenizer.cpp"
yy5:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case ' ':
			yyt1 = YYCURSOR;
			goto yy56;
		case '\n':
			yyt1 = YYCURSOR;
			goto yy57;
		default: goto yy6;
	}
yy6:
#line 168 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::NEWLINE)); goto again; }
#line 216 "Tokenizer.cpp"
yy7:
	++YYCURSOR;
#line 165 "./tokenizer.re2c"
	{ goto again; }
#line 221 "Tokenizer.cpp"
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy58;
		default: goto yy3;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy10;
		case '"': goto yy62;
		default: goto yy59;
	}
yy10:
#line 87 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::ERRORTOKEN)); goto again; }
#line 239 "Tokenizer.cpp"
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy12;
		default: goto yy11;
	}
yy12:
#line 151 "./tokenizer.re2c"
	{ goto again; }
#line 249 "Tokenizer.cpp"
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy64;
		default: goto yy14;
	}
yy14:
#line 88 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::PERCENT, "%")); goto again; }
#line 259 "Tokenizer.cpp"
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy65;
		default: goto yy16;
	}
yy16:
#line 89 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::AMPER, "&")); goto again; }
#line 269 "Tokenizer.cpp"
yy17:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy18;
		default: goto yy67;
	}
yy18:
#line 86 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::ERRORTOKEN)); goto again; }
#line 280 "Tokenizer.cpp"
yy19:
	++YYCURSOR;
#line 90 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::LPAR, "(")); nesting++; goto again; }
#line 285 "Tokenizer.cpp"
yy20:
	++YYCURSOR;
#line 91 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::RPAR, ")")); nesting--; goto again; }
#line 290 "Tokenizer.cpp"
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy70;
		case '=': goto yy72;
		default: goto yy22;
	}
yy22:
#line 92 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::STAR, "*")); goto again; }
#line 301 "Tokenizer.cpp"
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy73;
		default: goto yy24;
	}
yy24:
#line 93 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::PLUS, "+")); goto again; }
#line 311 "Tokenizer.cpp"
yy25:
	++YYCURSOR;
#line 94 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::COMMA, ",")); goto again; }
#line 316 "Tokenizer.cpp"
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy74;
		case '>': goto yy75;
		default: goto yy27;
	}
yy27:
#line 95 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::MINUS, "-")); goto again; }
#line 327 "Tokenizer.cpp"
yy28:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy76;
		default: goto yy29;
	}
yy29:
#line 96 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::DOT, ".")); goto again; }
#line 338 "Tokenizer.cpp"
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case '/': goto yy77;
		case '=': goto yy79;
		default: goto yy31;
	}
yy31:
#line 97 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::SLASH, "/")); goto again; }
#line 349 "Tokenizer.cpp"
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy32;
		default: goto yy33;
	}
yy33:
	t1 = yyt1;
	t2 = YYCURSOR;
#line 76 "./tokenizer.re2c"
	{
            tokens.push_back(Token(TokenType::NUMBER, string(t1, t2 - t1)));
            goto again;
        }
#line 373 "Tokenizer.cpp"
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy80;
		default: goto yy35;
	}
yy35:
#line 98 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::COLON, ":")); goto again; }
#line 383 "Tokenizer.cpp"
yy36:
	++YYCURSOR;
#line 99 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::SEMI, ";")); goto again; }
#line 388 "Tokenizer.cpp"
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case '<': goto yy81;
		case '=': goto yy83;
		case '>': goto yy84;
		default: goto yy38;
	}
yy38:
#line 100 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::LESS, "<")); goto again; }
#line 400 "Tokenizer.cpp"
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy85;
		default: goto yy40;
	}
yy40:
#line 101 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::EQUAL, "=")); goto again; }
#line 410 "Tokenizer.cpp"
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy86;
		case '>': goto yy87;
		default: goto yy42;
	}
yy42:
#line 102 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::GREATER, ">")); goto again; }
#line 421 "Tokenizer.cpp"
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy89;
		default: goto yy44;
	}
yy44:
#line 103 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::AT, "@")); goto again; }
#line 431 "Tokenizer.cpp"
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy45;
		default: goto yy46;
	}
yy46:
	t1 = yyt1;
	t2 = YYCURSOR;
#line 81 "./tokenizer.re2c"
	{
            tokens.push_back(Token(TokenType::NAME, string(t1, t2 - t1)));
            goto again;
        }
#line 508 "Tokenizer.cpp"
yy47:
	++YYCURSOR;
#line 104 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::LSQB, "[")); nesting++; goto again; }
#line 513 "Tokenizer.cpp"
yy48:
	++YYCURSOR;
#line 105 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::RSQB, "]")); nesting--; goto again; }
#line 518 "Tokenizer.cpp"
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy90;
		default: goto yy50;
	}
yy50:
#line 106 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::CIRCUMFLEX, "^")); goto again; }
#line 528 "Tokenizer.cpp"
yy51:
	++YYCURSOR;
#line 107 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::LBRACE, "{")); nesting++; goto again; }
#line 533 "Tokenizer.cpp"
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy91;
		default: goto yy53;
	}
yy53:
#line 108 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::VBAR, "|")); goto again; }
#line 543 "Tokenizer.cpp"
yy54:
	++YYCURSOR;
#line 109 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::RBRACE, "}")); nesting--; goto again; }
#line 548 "Tokenizer.cpp"
yy55:
	++YYCURSOR;
#line 110 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::TILDE, "~")); goto again; }
#line 553 "Tokenizer.cpp"
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case ' ': goto yy56;
		case '\n': goto yy57;
		default:
			yyt2 = YYCURSOR;
			goto yy92;
	}
yy57:
	++YYCURSOR;
	t2 = yyt1;
	t1 = yyt1 - 1;
	t3 = YYCURSOR - 1;
#line 140 "./tokenizer.re2c"
	{
            YYCURSOR = t3;
            goto again;
        }
#line 574 "Tokenizer.cpp"
yy58:
	++YYCURSOR;
#line 112 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::NOTEQUAL, "!=")); goto again; }
#line 579 "Tokenizer.cpp"
yy59:
	yych = *++YYCURSOR;
yy60:
	switch (yych) {
		case '\n': goto yy61;
		case '"': goto yy94;
		default: goto yy59;
	}
yy61:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
		case 0: goto yy10;
		case 1: goto yy18;
		case 2: goto yy29;
		case 3: goto yy63;
		case 4: goto yy69;
		default: goto yy109;
	}
yy62:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy63;
		case '"': goto yy95;
		default: goto yy59;
	}
yy63:
	t1 = yyt1;
#line 157 "./tokenizer.re2c"
	{
            tokens.push_back(Token(TokenType::STRING, string(t1, YYCURSOR - t1)));
            goto again;
        }
#line 613 "Tokenizer.cpp"
yy64:
	++YYCURSOR;
#line 113 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::PERCENTEQUAL, "%=")); goto again; }
#line 618 "Tokenizer.cpp"
yy65:
	++YYCURSOR;
#line 114 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::AMPEREQUAL, "&=")); goto again; }
#line 623 "Tokenizer.cpp"
yy66:
	yych = *++YYCURSOR;
yy67:
	switch (yych) {
		case '\n': goto yy61;
		case '\'': goto yy68;
		default: goto yy66;
	}
yy68:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy69;
		case '\'': goto yy68;
		default: goto yy66;
	}
yy69:
	t1 = yyt1;
#line 161 "./tokenizer.re2c"
	{
            tokens.push_back(Token(TokenType::STRING, string(t1, YYCURSOR - t1)));
            goto again;
        }
#line 647 "Tokenizer.cpp"
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy96;
		default: goto yy71;
	}
yy71:
#line 115 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::DOUBLESTAR, "**")); goto again; }
#line 657 "Tokenizer.cpp"
yy72:
	++YYCURSOR;
#line 116 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::STAREQUAL, "*=")); goto again; }
#line 662 "Tokenizer.cpp"
yy73:
	++YYCURSOR;
#line 117 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::PLUSEQUAL, "+=")); goto again; }
#line 667 "Tokenizer.cpp"
yy74:
	++YYCURSOR;
#line 118 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::MINEQUAL, "-=")); goto again; }
#line 672 "Tokenizer.cpp"
yy75:
	++YYCURSOR;
#line 119 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::RARROW, "->")); goto again; }
#line 677 "Tokenizer.cpp"
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy97;
		default: goto yy61;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy98;
		default: goto yy78;
	}
yy78:
#line 120 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::DOUBLESLASH, "//")); goto again; }
#line 693 "Tokenizer.cpp"
yy79:
	++YYCURSOR;
#line 121 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::SLASHEQUAL, "/=")); goto again; }
#line 698 "Tokenizer.cpp"
yy80:
	++YYCURSOR;
#line 122 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::COLONEQUAL, ":=")); goto again; }
#line 703 "Tokenizer.cpp"
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy99;
		default: goto yy82;
	}
yy82:
#line 123 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::LEFTSHIFT, "<<")); goto again; }
#line 713 "Tokenizer.cpp"
yy83:
	++YYCURSOR;
#line 124 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::LESSEQUAL, "<=")); goto again; }
#line 718 "Tokenizer.cpp"
yy84:
	++YYCURSOR;
#line 125 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::NOTEQUAL, "<>")); goto again; }
#line 723 "Tokenizer.cpp"
yy85:
	++YYCURSOR;
#line 126 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::EQEQUAL, "==")); goto again; }
#line 728 "Tokenizer.cpp"
yy86:
	++YYCURSOR;
#line 127 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::GREATEREQUAL, ">=")); goto again; }
#line 733 "Tokenizer.cpp"
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy100;
		default: goto yy88;
	}
yy88:
#line 128 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::RIGHTSHIFT, ">>")); goto again; }
#line 743 "Tokenizer.cpp"
yy89:
	++YYCURSOR;
#line 129 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::ATEQUAL, "@=")); goto again; }
#line 748 "Tokenizer.cpp"
yy90:
	++YYCURSOR;
#line 130 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::CIRCUMFLEXEQUAL, "^=")); goto again; }
#line 753 "Tokenizer.cpp"
yy91:
	++YYCURSOR;
#line 131 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::VBAREQUAL, "|=")); goto again; }
#line 758 "Tokenizer.cpp"
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy93;
		default: goto yy92;
	}
yy93:
	t2 = yyt1;
	t3 = yyt2;
	t1 = yyt1 - 1;
#line 145 "./tokenizer.re2c"
	{
            processIndent(tokens, ind, nesting, (char*)t2, (char*)t3);
            YYCURSOR = t3;
            goto again;
        }
#line 775 "Tokenizer.cpp"
yy94:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy63;
		case '"': goto yy94;
		default: goto yy59;
	}
yy95:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy104;
yy96:
	++YYCURSOR;
#line 133 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::DOUBLESTAREQUAL, "**=")); goto again; }
#line 792 "Tokenizer.cpp"
yy97:
	++YYCURSOR;
#line 134 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::ELLIPSIS, "...")); goto again; }
#line 797 "Tokenizer.cpp"
yy98:
	++YYCURSOR;
#line 135 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::DOUBLESLASHEQUAL, "//=")); goto again; }
#line 802 "Tokenizer.cpp"
yy99:
	++YYCURSOR;
#line 136 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::LEFTSHIFTEQUAL, "<<=")); goto again; }
#line 807 "Tokenizer.cpp"
yy100:
	++YYCURSOR;
#line 137 "./tokenizer.re2c"
	{ tokens.push_back(Token(TokenType::RIGHTSHIFTEQUAL, ">>=")); goto again; }
#line 812 "Tokenizer.cpp"
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n':
		case '.': goto yy101;
		case '"': goto yy105;
		default: goto yy61;
	}
yy102:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy63;
		case '"': goto yy106;
		default: goto yy59;
	}
yy103:
	yych = *++YYCURSOR;
yy104:
	switch (yych) {
		case '\n': goto yy101;
		case '"': goto yy102;
		case '.': goto yy103;
		default: goto yy59;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"': goto yy107;
		default: goto yy61;
	}
yy106:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy63;
		case '"': goto yy108;
		default: goto yy59;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"': goto yy110;
		default: goto yy61;
	}
yy108:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy109;
		default: goto yy60;
	}
yy109:
	t1 = yyt1;
#line 153 "./tokenizer.re2c"
	{
            tokens.push_back(Token(TokenType::STRING, string(t1, YYCURSOR - t1)));
            goto again;
        }
#line 872 "Tokenizer.cpp"
yy110:
	++YYCURSOR;
	goto yy109;
}
#line 177 "./tokenizer.re2c"

done:
   return tokens;
}
