name: PyserTest
on: [push]
jobs:
  Pyser-Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: 'x64'
    - run: python3.10 -m pip install astpretty
    - run: mkdir tmp && mkdir build
    - run: cd build && cmake .. && make -j4 && cd ..
    - run: python3.10 test.py
